# Generated by Django 3.2.22 on 2024-01-05 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preview", models.CharField(max_length=155, null=True)),
                ("title", models.CharField(max_length=250, null=True)),
                ("price", models.FloatField(null=True)),
                ("story", models.TextField(null=True)),
                ("cover_image", models.CharField(max_length=155, null=True)),
                ("video_or_sound", models.CharField(max_length=155, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
